name: holdemmanager_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  intl: ^0.17.0
  shared_preferences: ^2.2.3
  get: 4.6.6
  flutter_locales: 2.0.0
  restart_app: 1.2.1
  carousel_slider: ^4.0.0

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  path_provider: ^2.0.11
  flutter_image_compress: ^2.3.0
  path: ^1.8.3
  http: ^1.2.1
  flutter_form_builder: ^9.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:
  assets:
    - lib/assets/images/image-poker.jpg
    - lib/assets/images/default-user.png
    - lib/assets/locales/traducciones.json
    - lib/assets/images/ingles.jpg
    - lib/assets/images/espaÃ±ol.jpg
    - lib/assets/images/portugues.jpg

  uses-material-design: true

  
